"""Centralized Risk Manager.

Evaluates every trade signal against all risk guards before execution.
Returns a JSON-compatible decision: APPROVED, REJECTED, or MODIFIED.
"""

from __future__ import annotations

import pandas as pd
from typing import Any
from loguru import logger

from config.settings import Settings
from portfolio.portfolio_state import PortfolioState
from signals.signal import SignalType, TradeSignal

from risk.position_sizing import AdvancedPositionSizer
from risk.stop_loss import StopLossEngine
from risk.take_profit import TakeProfitEngine
from risk.drawdown_guard import DrawdownGuard
from risk.exposure_manager import ExposureManager
from risk.leverage_manager import LeverageManager
from risk.volatility_filter import VolatilityFilter
from risk.correlation_filter import CorrelationFilter
from risk.daily_loss_guard import DailyLossGuard
from risk.portfolio_risk import PortfolioRisk
from risk.risk_report import RiskReport


class RiskManager:
    """Orchestrates all risk checks and sizing modifications."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        
        # Initialize all guards and engines
        self.sizer = AdvancedPositionSizer(settings.strategy, settings.risk)
        self.sl_engine = StopLossEngine()
        self.tp_engine = TakeProfitEngine()
        
        self.drawdown_guard = DrawdownGuard(settings.risk)
        self.exposure_manager = ExposureManager(settings.risk)
        self.leverage_manager = LeverageManager(settings.strategy)
        self.volatility_filter = VolatilityFilter()
        self.correlation_filter = CorrelationFilter(settings.risk)
        self.daily_loss_guard = DailyLossGuard(settings.risk)
        
        self.portfolio_risk = PortfolioRisk(settings.risk)
        self.risk_report = RiskReport(self.portfolio_risk)

    def evaluate_trade(
        self,
        signal: TradeSignal,
        latest_data: pd.Series,
        portfolio: PortfolioState,
    ) -> dict[str, Any]:
        """Evaluate a proposed trade signal.

        Args:
            signal: The raw signal generated by the Strategy Engine.
            latest_data: The latest OHLCV bar with features.
            portfolio: Current state of the portfolio.

        Returns:
            Dictionary with 'approved', 'reason', and execution parameters.
        """
        # If HOLD, just reject outright
        if signal.signal == SignalType.HOLD:
            return self._reject("Original signal is HOLD")

        # 1. Global Portfolio Guards (Are we even allowed to trade?)
        if not self.drawdown_guard.is_safe(portfolio):
            return self._reject("Drawdown limit exceeded")
            
        if not self.daily_loss_guard.is_safe(portfolio, signal.timestamp):
            return self._reject("Daily loss limit or consecutive losers exceeded")

        # 2. Market Condition Filters
        if not self.volatility_filter.is_safe(signal, latest_data):
            return self._reject("Extreme volatility or gap detected")
            
        # Target symbol is attached to settings for now (or passed in)
        target_symbol = self.settings.symbol
        if not self.correlation_filter.is_safe(target_symbol, portfolio):
            return self._reject("High correlation with open positions")

        # 3. Parameter Calculation (Stops and Targets)
        # We recalculate these via the advanced engines just in case
        stop_loss = self.sl_engine.calculate_initial_stop(
            latest_data, signal.entry, signal.signal,
            method="atr", atr_multiplier=self.settings.strategy.atr_multiplier_stop_loss
        )
        
        take_profit = self.tp_engine.calculate_target(
            latest_data, signal.entry, stop_loss, signal.signal,
            method="fixed_rr", rr_ratio=2.0
        )
        
        # 4. Position Sizing
        size = self.sizer.calculate_size(
            portfolio=portfolio,
            entry_price=signal.entry,
            stop_loss=stop_loss,
            method="atr_risk"  # Can be configured
        )
        
        if size <= 0:
            return self._reject("Position sizer returned 0 units (Risk too high or capital too low)")

        # 5. Exposure and Leverage Checks
        fiat_size = size * signal.entry
        if not self.exposure_manager.is_safe(target_symbol, fiat_size, portfolio):
            return self._reject("Exposure limit exceeded")
            
        if not self.leverage_manager.validate_leverage(self.settings.strategy.leverage):
            return self._reject("Leverage limits exceeded")

        # 6. Final Approval
        risk_amount = abs(signal.entry - stop_loss) * size
        reward_amount = abs(take_profit - signal.entry) * size
        risk_reward = reward_amount / risk_amount if risk_amount > 0 else 0.0
        
        # Recompute portfolio exposure stats post-trade
        projected_exposure = portfolio.total_exposure + fiat_size
        projected_equity = portfolio.total_equity
        portfolio_exposure_pct = projected_exposure / projected_equity if projected_equity > 0 else 0.0

        return {
            "approved": True,
            "reason": "Risk checks passed",
            "position_size": size,
            "risk_amount": risk_amount,
            "stop_loss": stop_loss,
            "take_profit": take_profit,
            "risk_reward": risk_reward,
            "portfolio_exposure": portfolio_exposure_pct,
            "drawdown": portfolio.account.get_drawdown(projected_equity)
        }

    def _reject(self, reason: str) -> dict[str, Any]:
        """Helper to return a rejected decision."""
        logger.info(f"Trade Rejected by Risk Manager: {reason}")
        return {
            "approved": False,
            "reason": reason,
            "position_size": 0.0,
            "risk_amount": 0.0,
            "stop_loss": 0.0,
            "take_profit": 0.0,
            "risk_reward": 0.0,
            "portfolio_exposure": 0.0,
            "drawdown": 0.0
        }
