"""Trade signal definitions and data structures.

This module defines the fundamental output of the Strategy Engine:
a structured trade signal indicating action, pricing, and rationale.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class SignalType(str, Enum):
    """Allowed trading actions."""

    BUY = "BUY"
    SELL = "SELL"
    SHORT = "SHORT"
    COVER = "COVER"
    HOLD = "HOLD"


@dataclass
class TradeSignal:
    """A complete trading signal generated by a strategy.

    Attributes:
        timestamp: When the signal was generated (UTC).
        regime: The market regime active when generated.
        strategy: Name of the strategy that produced the signal.
        signal: The trading action (e.g., BUY, HOLD).
        confidence: Strategy confidence score (0.0 to 1.0).
        entry: Target entry price.
        stop_loss: Target stop-loss price.
        take_profit: Target take-profit price.
        risk_reward: Calculated risk-to-reward ratio.
        reason: List of rule justifications for the signal.
    """

    timestamp: datetime
    regime: str
    strategy: str
    signal: SignalType
    confidence: float
    entry: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    risk_reward: float = 0.0
    reason: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert the signal to a JSON-serializable dictionary.

        Returns:
            Dictionary representation of the signal.
        """
        data = asdict(self)
        data["timestamp"] = self.timestamp.isoformat()
        data["signal"] = self.signal.value
        return data

    @classmethod
    def create_hold(
        cls,
        timestamp: datetime,
        regime: str,
        strategy: str,
        reason: str | list[str],
    ) -> "TradeSignal":
        """Convenience method to create a HOLD signal.

        Args:
            timestamp: Signal time.
            regime: Current market regime.
            strategy: Strategy name.
            reason: Explanation for holding.

        Returns:
            A populated HOLD ``TradeSignal``.
        """
        reasons = [reason] if isinstance(reason, str) else reason
        return cls(
            timestamp=timestamp,
            regime=regime,
            strategy=strategy,
            signal=SignalType.HOLD,
            confidence=1.0,
            reason=reasons,
        )
